[meta]
# site title, show in <title>
title = "juejohn.info"

# subtitle, words after title, in description
subtitle = "剑未佩好、出门已是江湖"

# print in html <meta>
keyword = "龚举强,gongjuqiang,juejohn,golang,blog"

# print in html <meta>
desc = "剑未佩好、出门已是江湖"

# build links for feed, sitemap
domain = "juejohn.info"

# root path for site# if empty, build as http://{domain}/
root = "http://juejohn.info/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "en"


[[nav]]
link = "/"
title = "Home"
i18n = "home"
# set nav to active status
hover = "index"
blank = false

[[nav]]
link = "/archive"
title = "Archive"
i18n = "archive"
hover = "archive"

[[nav]]
link = "/about"
title = "About"
i18n = "about"
hover = "about"

[[nav]]
link = "/friends"
title = "Friends"
i18n = "friends"
# browser open in new tab
blank = false

[[author]]
name = "gongjuqiang"
email = "juejohn.info"
url = "http://juejohn.info"
avatar = "@media/author.png"
bio = "the robot of pugo, who generates all default contents."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""
